name: ReservedFilesChecker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  #DO NOT CHANGE
  #workflow_dispatch:
  push:
    branches: [ master , main ]
    #paths-ignore:
    #- ".github/workflows/UP*.yml"
    paths: #ALL RESERVED FILES HERE
    # Don't touch MY files!!!!
    - ".Ossonts/CopyTemplateFilesToRepo.sh"
    - ".Ossonts/RemoveReservedFiles.sh"
    - ".Ossonts/SHALogger.sh"
    - ".Ossonts/Update.md"
    - ".Ossonts/mlc.json"
    - ".Ossonts/README.md"
    - ".Ossonts/ReservedFilesChecker.sh"
    - ".Ossonts/Trigger.md"
    - ".Ossonts/latexHeader.tex"
    - ".Ossonts/pandoc.yml"
    - ".github/workflows/*"
    - ".github/workflows/CheckForUpdates.yml"
    - ".github/workflows/Pandoc.yml"
    - ".github/workflows/ReservedFilesChecker.yml"
    #- ".github/workflows/StudentWorkflow.yml"
    - ".github/workflows/MarkdownChecker.yml"
    - ".github/workflows/PortfolioAdvisor.yml"
    - ".github/workflows/SHALogger.yml"
    #- ".github/workflows/StudentWorkflowMatrix.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-20.04
    #runs-on: [self-hosted, linux, x64]
    runs-on: [self-hosted, linux, x64,L1]
    #container: ossonts/setap:latest # Beware of versioning here DOCKERHUB
    container:
       image: ghcr.io/setap2021/setapdocker   # Beware of versioning here GITHUB -- Some kind of magic here
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.actor != 'Ossonts'}} # Not by me - hey I know it is you!!
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Find out what you did and who you are....

        run: |
          pwd
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_SHA"
          echo "$GITHUB_ACTOR"
          gh --version
          chmod +x  .Ossonts/ReservedFilesChecker.sh
          .Ossonts/ReservedFilesChecker.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # # Commit auto generated files
      # - uses: EndBug/add-and-commit@v5 # this gave merge errors
      #   with:
      #     message: "Logging submit SHA"
      #     branch: feedback
      #     add: ".Ossonts/*.log .Ossonts/*.md --force"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: github-actions-x/commit@v2.6
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     rebase: 'true'
      #     #push-branch: 'feedback' # does not quite work yet
      #     commit-message: 'SHA-Logger'
      #     force-add: 'true'
      #     files: .Ossonts/*.log .Ossonts/*.md
      #     name: OssontsBOT
      #     #email: my.github@email.com
